apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.bot.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector: { app: {{ .Values.service.bot.name }} }
  ports:
    - name: http
      port: {{ .Values.service.bot.port }}
      targetPort: 8088