apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.core.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector: { app: {{ .Values.service.core.name }} }
  ports:
    - name: http
      port: {{ .Values.service.core.port }}
      targetPort: 8080
