apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ required "secrets.db.pass is required" .Values.secrets.db.pass | quote }}
  DADATA_TOKEN: {{ required "secrets.dadata.token is required" .Values.secrets.dadata.token | quote }}
  DADATA_SECRET: {{ required "secrets.dadata.secret is required" .Values.secrets.dadata.secret | quote }}
  TWOGIS_API_KEY: {{ required "secrets.twogis.key is required" .Values.secrets.twogis.key | quote }}
  TELEGRAM_BOT_TOKEN: {{ required "secrets.tg.botToken is required" .Values.secrets.tg.botToken | quote }}
  TELEGRAM_BOT_USER_NAME: {{ required "secrets.tg.botToken is required" .Values.secrets.tg.botName | quote }}
